### ISSUE TITLE
Cannot change mipi clock rate

### ISSUE THREAD

**Issue by bswhite1** [SamsungARTIK/linux-artik#11]
Trying to create a new display driver for a 320x480 1-lane mipi display. Followed instructions in the Artik_Software_Developer_Guide_v1.4. Appears we are attempting to use new driver. However the mipi clock always outputs 800Mhz, no matter how I configure the dtsi. 

In the dtsi under dp_drm_mipi, dp_control, I have attempted to changed the "clk_src_lv0" and "clk_div_lv0".  Through adding debugging, I can see that the functions "nx_disp_top_clkgen_set_clock_source" and "nx_disp_top_clkgen_set_clock_divisor" are getting called with the values I have modified. The clock stays at 800Mhz no matter what I change them to.

I also tried writing the correct values straight to the register. Within clk-s5pxx18-pll.c I manually hardcoded the value for "sys-disspclk id 16" register to the clock rate I wanted. Again, with no change to the 800 Mhz.

**Comment by cometzero** [comment]
Hi @bswhite1,

800MHz is source clock of display parts and it indicates PLL3 clock source. You already read below document but I revoke it once again to explain in here. First of all, you should calculate pixel clock of your display. You may find it from a datasheet of the display or you can calculate it by using resolutions and front/back porch values.

Please see [display-timings.txt](https://www.kernel.org/doc/Documentation/devicetree/bindings/display/panel/display-timing.txt) of kernel document.


The artik710/artik530 use two level clock source/divider configurations(clk_src_lv0|1 and clk_div_lv0|1).
- clk_src_lv0 = <3>; Typically, the display clock uses PLL3 and it generates 800MHz clock source.
   0 = PLL[0] 1 = PLL[1] 2 = PLL[2] 3 = PLL[3] 4 = HDMI PLL Clock 5 = Reserved 6 = Reserved
- clk_div_lv0 = <6>; Clock divider level0. It means we can get (50MHz -> 133MHz) clock output from the divider value(800MHz / 6 = 133MHz)
- clk_src_lv1 = <7>; Clock source level1. The value "7" means "Divided Clock from Divider 0". So, it will be (50MHz -> 133MHz) clock which is from the clk_div_lv0.
  0 = PLL[0] 1 = PLL[1] 2 = PLL[2] 3 = PLL[3] 4 = HDMI PLL Clock 5 = Reserved 6 = Reserved 7 = Divided Clock from Divider 0
- clk_div_lv0 = <1>; Clock divider level1. It can divide the source level1 clock.
Finally, this MIPI-DSI panel will have 133MHz input source clock and it can be an apromixation of the 130.36MHz sync clock.

**Comment by cometzero** [comment]
Hi,
Setting a pixel clock indicates DPC/MLC (Display controller) IP can generate a frame with the clock. MIPI-DSI clock should be set in different place. As you can see Device tree setting from s5p4418-artik530-raptor-common.dtsi, hs_bitrate and lp_bitrate indicate MIPI-DSI's pll clock configurations. hs_bitrate: 960Mbps will set 960MHz of MIPI-DSI pll clock. You can check it 480MHz(DDR source-sync clock) output clock through MIPIDSI_D[P/N]CLK_F pins.

&dp_drm_mipi {                                                                  
        hs_bitrate = <960>;                                                     
        lp_bitrate = <100>;
