### ISSUE TITLE
I want to install toolchain. But the "wget" link is not correct.

### ISSUE THREAD

**Issue by sauber92** [SamsungARTIK/linux-artik#3]
I read your **README.md**.  

You wrote `wget http://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz` at **2.1 Install cross compiler**  

However, my PC(Ubuntu 14.04.3 LTS) is in ERROR 404.

The console printed this.

```
ubuntu@ubuntu-desktop:~$ wget http://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
--2016-11-22 19:46:15--  http://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
Resolving releases.linaro.org (releases.linaro.org)... 52.221.254.75
Connecting to releases.linaro.org (releases.linaro.org)|52.221.254.75|:80... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2016-11-22 19:46:24 ERROR 404: NOT FOUND.
```  

How can I do?

**Comment by cometzero** [comment]
Hi, the link has been broken since released new toolchain.
Try below:
wget http://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
